version: "3.8"

services:
  # Banco de Dados
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WordPress escalável
  wordpress:
    image: wordpress:5.4.2-php7.2-apache
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-data:/var/www/html

  # Balanceador de carga
  nginx:
    image: nginx:1.19.0
    container_name: nginx_balancer
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress

  # Teste de carga
  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
      - ./resultados:/mnt/resultados
    working_dir: /mnt/locust
    command: -f locustfile.py --host http://nginx
    depends_on:
      - nginx